service: curso-node-serverless
frameworkVersion: '3'

params:
  default:
    dbName: *****
  dev:
    connectionString: *****

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    MONGODB_CONNECTIONSTRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}

plugins:
  - serverless-offline

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

  sendResults:
    handler: /api/handlers.sendResults
    events:
      - httpApi:
          path: /send-results
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/sendResponse.json)}
  getResult:
    handler: /api/handlers.getResult
    events:
      - httpApi:
          path: /result/{id}
          method: get
