service: curso-node-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

  sendResults:
    handler: /api/handlers.sendResults
    events:
      - httpApi:
          path: /send-results
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/sendResponse.json)}
